import { Connection } from './Connection';

export default Connection;

export * from './Connection';
export * from './api/Bluetooth';
export * from './api/Cradle';
export * from './api/Cwmp';
export * from './api/DDns';
export * from './api/Device';
export * from './api/Dhcp';
export * from './api/Diagnosis';
export * from './api/DialUp';
export * from './api/FileManager';
export * from './api/Global';
export * from './api/Host';
export * from './api/Language';
export * from './api/Lan';
export * from './api/Led';
export * from './api/Log';
export * from './api/MLog';
export * from './api/Monitoring';
export * from './api/Net';
export * from './api/Ntwk';
export * from './api/OnlineUpdate';
export * from './api/Ota';
export * from './api/Pb';
export * from './api/Pin';
export * from './api/Redirection';
export * from './api/SdCard';
export * from './api/Security';
export * from './api/Sms';
export * from './api/SNtp';
export * from './api/Statistic';
export * from './api/Syslog';
export * from './api/TimeRule';
export * from './api/Time';
export * from './api/UsbPrinter';
export * from './api/UsbStorage';
export * from './api/User';
export * from './api/Voice';
export * from './api/Vpn';
export * from './api/VSim';
export * from './api/WebServer';
export * from './api/WLan';

